name: Deploy Frontend to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Test SSH Connection
        run: |
          ssh -o BatchMode=yes -o ConnectTimeout=15 -o StrictHostKeyChecking=no ubuntu@ec2-3-27-124-5.ap-southeast-2.compute.amazonaws.com "echo SSH_OK"

      - name: Deploy ke EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@ec2-3-27-124-5.ap-southeast-2.compute.amazonaws.com << 'EOF'
          set -e
          cd ~/frontend_pelayanan_publik
          git pull origin master
          export PUBLIC_API_URL='/api'
          export VITE_API_URL='/api'
          npm ci
          npm run build
          sudo mkdir -p /var/www/pelayanan_publik
          sudo rsync -az --delete dist/ /var/www/pelayanan_publik/
          sudo systemctl restart nginx
          EOF
